# Vagrant config for web

Vagrant.configure("2") do |config|


#    config.landrush.enabled = true
#    config.landrush.tld = "lo"

    config.vm.box = "ubuntu/trusty64"
    config.vm.host_name = "djangobox.lo"
#    config.vm.network "private_network", type: "dhcp"
    config.vm.network "public_network", ip: "192.168.1.37"
    config.vm.synced_folder "D:/Sites/searchengine", "/home/vagrant/project/"

    config.ssh.forward_agent = true
    config.ssh.insert_key = false

    config.vm.provision "file", source: "config/Envfile", destination: "/home/vagrant/.Envfile"
    config.vm.provision "shell", keep_color: true, privileged: false, path: "config/init.sh"
    config.vm.provision "shell", keep_color: true, privileged: false, path: "config/packages.sh"
    config.vm.provision "shell", keep_color: true, privileged: false, path: "config/setup.sh"

    config.vm.post_up_message = "Puedes acceder a la VM usando la siguiente dirección: djangobox.lo"
end
